// pokemon-kanto — tools/blurbs.js
// Original Pokédex flavour text, one line per species. These are written for
// this project; none of the real dex entries are reproduced. Keep them to a
// single sentence that fits the dex screen's two wrapped lines.
//
// gen_data.js will refuse to emit a species file if any of the 151 is missing.

module.exports = {
  // ---- #001-020 ----------------------------------------------------------
  bulbasaur:  'The bulb on its back was planted at birth and grows with it, feeding on the same sunlight.',
  ivysaur:    'When the bud grows heavy enough that it can no longer stand upright, bloom is close.',
  venusaur:   'Its flower turns to follow the sun all day, and the whole clearing smells sweet by evening.',
  charmander: 'The flame at its tail burns low when it sleeps and gutters badly when it is unwell.',
  charmeleon: 'It seeks out strong opponents on purpose, and the tail flame burns blue-white when it finds one.',
  charizard:  'It can melt stone, so it climbs high and breathes upward, away from anything that might catch.',
  squirtle:   'The shell is not just armour — the curve of it makes the creature faster in water than out.',
  wartortle:  'Its tail is said to darken and thicken with age, and old ones are treated with real respect.',
  blastoise:  'It braces its legs and locks its knees before firing, or the recoil would knock it flat.',
  caterpie:   'Its feet grip so well it can walk up glass, though the smell it releases when frightened is dreadful.',
  metapod:    'The shell is hard but the creature inside is soft, so it does nothing all day but wait.',
  butterfree: 'The dust on its wings repels water, letting it forage in rain when nothing else will.',
  weedle:     'The barb on its head carries a poison strong enough to make a grown hiker sit down.',
  kakuna:     'It can barely move, but it can raise its temperature enough to discourage anything curious.',
  beedrill:   'They defend a nest as one. Disturbing a single one is a mistake you make only once.',
  pidgey:     'It kicks up sand to blind whatever is bothering it, then simply leaves rather than fight.',
  pidgeotto:  'It claims a wide territory and patrols the whole boundary daily, driving off every rival.',
  pidgeot:    'At full speed the air behind it cracks, and the crest feathers lie flat against its skull.',
  rattata:    'Its teeth never stop growing, so it gnaws constantly — through wood, wire and sometimes walls.',
  raticate:   'It swims well, using its whiskers to judge the current, and will cross a river to reach food.',

  // ---- #021-040 ----------------------------------------------------------
  spearow:    'Too poor a flier to travel far, so it stays low, loud and extremely bad-tempered.',
  fearow:     'The long neck and beak let it strike into soil or water without slowing its flight.',
  ekans:      'It unhinges its jaw to swallow eggs whole, and lies still for days afterwards.',
  arbok:      'The pattern on its hood differs by region, and each pattern is said to mean something.',
  pikachu:    'It discharges into the ground when startled, which is why nothing grows where a colony sleeps.',
  raichu:     'The tail is an earthing rod. Without it the creature would shock itself with its own charge.',
  sandshrew:  'It curls up so tightly that the seams of its hide vanish, and simply lets danger pass.',
  sandslash:  'The spines are hardened hide, and it sheds and regrows them after a hard season.',
  nidoranf:   'Small and cautious, but the horn carries venom, and it will use it without warning.',
  nidorina:   'It grows calmer as it matures, and will place itself between danger and anything smaller.',
  nidoqueen:  'The overlapping scales stiffen when it tenses, turning its whole body into a shield.',
  nidoranm:   'It listens with those oversized ears and stands very still, deciding whether to run or charge.',
  nidorino:   'The horn is harder than diamond drill bits, and it tests this on rocks constantly.',
  nidoking:   'One swing of that tail can snap a transmission tower. It is not a creature for cities.',
  clefairy:   'Sightings cluster around Mt. Moon on clear nights, which has never been satisfactorily explained.',
  clefable:   'It hears a pin drop half a mile off, which is why almost nobody has ever seen one up close.',
  vulpix:     'It is born with one white tail that splits as it grows. Six is the usual end state.',
  ninetales:  'Its eyes are unsettling to meet, and the old stories about grudges are told very seriously.',
  jigglypuff: 'It inflates its lungs to sing longer than anything listening can stay awake.',
  wigglytuff: 'The fur is famously fine, and the creature is famously unwilling to let you touch it.',

  // ---- #041-060 ----------------------------------------------------------
  zubat:       'It has no eyes at all. In daylight it is helpless, so it simply never goes out in it.',
  golbat:      'It drinks until it is too heavy to fly, then drops off and waddles away, which is worse.',
  oddish:      'It buries itself by day and walks on its roots at night, seeking richer soil.',
  gloom:       'The smell carries two miles downwind. A small number of people insist they like it.',
  vileplume:   'The largest petals in Kanto, and every one of them loaded with allergenic pollen.',
  paras:       'The mushrooms are in charge. The bug is, increasingly, along for the ride.',
  parasect:    'By this stage the fungus has won entirely, and what walks is the mushroom.',
  venonat:     'Those compound eyes see in the dark, which is when the insects it eats are out.',
  venomoth:    'The scales it sheds are fine enough to hang in the air for an hour after it has gone.',
  diglett:     'Nobody agrees on what is below the neck, because nobody has ever managed to see it.',
  dugtrio:     'Three heads working one tunnel network, moving earth faster than any machine.',
  meowth:      'It collects round shiny things with no interest in their value, only their shine.',
  persian:     'It moves without sound on those pads, and the gem on its brow is harder than it looks.',
  psyduck:     'The headache is constant. When it gets bad enough, things around it start to move.',
  golduck:     'A superb swimmer that appears entirely calm, which the headaches suggest is a performance.',
  mankey:      'It is angry when it wakes up and the day generally goes downhill from there.',
  primeape:    'It will chase whatever annoyed it until one of them stops, and it does not stop.',
  growlithe:   'Fiercely loyal, and it remembers a scent for years. Guards across Kanto swear by them.',
  arcanine:    'Old texts call it the legendary dog. It covers ground fast enough to make that believable.',
  poliwag:     'The spiral is its innards showing through skin too thin to hide them.',

  // ---- #061-080 ----------------------------------------------------------
  poliwhirl:   'It can breathe air but hates being dry, and will find water within the hour.',
  poliwrath:   'Muscle all the way through. It swims against a river current without visible effort.',
  abra:        'It sleeps eighteen hours a day and teleports away the moment anything approaches.',
  kadabra:     'The spoon focuses the power. Bending it is a nervous habit, not a trick.',
  alakazam:    'Its brain never stops growing, and its head is too heavy for its neck to hold up unaided.',
  machop:      'It trains constantly and can lift things several times its own weight without strain.',
  machoke:     'The belt is not decoration — it is a restraint, and taking it off is discouraged.',
  machamp:     'Four arms throwing punches faster than the eye follows. It cannot do fine work at all.',
  bellsprout:  'The body is thin enough to sway in a breeze, and the roots pull free to let it walk.',
  weepinbell:  'It hangs from a branch by its hook and waits, entirely still, for something to land.',
  victreebel:  'The pitcher smells like honey. What is at the bottom of it is not honey.',
  tentacool:   'Almost entirely water. On the beach it is a puddle with two red gems in it.',
  tentacruel:  'Eighty tentacles, each one able to sting. Fishing fleets have a signal for spotting them.',
  geodude:     'Climbers regularly rest their hand on one, and regularly regret it.',
  graveler:    'It descends mountains by rolling and does not steer, which is a problem for everyone below.',
  golem:       'The shell is shed once a year and the discarded piece is strong enough to build with.',
  ponyta:      'It is born unsteady, but within a day it can outrun anything else on the route.',
  rapidash:    'At full gallop the mane is a solid sheet of flame and it becomes hard to look at directly.',
  slowpoke:    'It takes several seconds to register pain, which it seems not to mind at all.',
  slowbro:     'The thing on its tail bit down and never let go, and somehow both have benefited.',

  // ---- #081-100 ----------------------------------------------------------
  magnemite:   'It hangs in the air on its own magnetism and drifts toward anything carrying current.',
  magneton:    'Three fused into one. Nearby radios stop working and the temperature climbs.',
  farfetchd:   'It will not be parted from its stalk, and will fight anything that tries.',
  doduo:       'The two heads sleep in shifts, so something is always watching the horizon.',
  dodrio:      'Three heads means three moods, and they are frequently in disagreement.',
  seel:        'It is happiest in water cold enough to hurt, and hunts comfortably under sheet ice.',
  dewgong:     'It sleeps on floating ice and is almost impossible to distinguish from it.',
  grimer:      'It was sludge before it was alive, and where it walks, nothing grows for a season.',
  muk:         'The smell is genuinely dangerous at close range. Handlers work in shifts.',
  shellder:    'The shell is harder than the tongue is long, and the tongue is what you should watch.',
  cloyster:    'Nothing on record has broken that shell from the outside. People have tried.',
  gastly:      'Mostly gas, held together by something nobody has satisfactorily identified.',
  haunter:     'It passes through walls, which it finds far more entertaining than you will.',
  gengar:      'On a bright day your shadow may not quite match you. That is the usual warning.',
  onix:        'It tunnels at speed, and the rock it swallows on the way is what it is made of.',
  drowzee:     'It eats dreams, and prefers pleasant ones, which is bad luck for whoever was having them.',
  hypno:       'The pendulum is real and it works. Keep your eyes on its feet instead.',
  krabby:      'The pincers regrow if lost, though the new one comes back the wrong size for a while.',
  kingler:     'The oversized claw can crush steel but is so heavy it can barely aim it.',
  voltorb:     'It looks exactly like a discarded ball, which is the whole of its strategy.',

  // ---- #101-120 ----------------------------------------------------------
  electrode:   'Storing more charge than it can hold makes it irritable, and then makes it explode.',
  exeggcute:   'Six of them, and they communicate constantly. A separated one becomes distressed.',
  exeggutor:   'Each head thinks independently, and a head that thinks too hard simply drops off.',
  cubone:      'The skull it wears belonged to its mother. It has never been seen without it.',
  marowak:     'It has learned to throw the bone and catch it returning, and it does not miss.',
  hitmonlee:   'The legs extend on impact, which is why the kick lands from further away than looked possible.',
  hitmonchan:  'It works in three-minute rounds out of habit and will not be hurried.',
  lickitung:   'The tongue is twice its body length and it uses it the way you would use a hand.',
  koffing:     'It floats because what is inside it is lighter than air, and considerably worse for you.',
  weezing:     'Two bodies sharing one supply of gas, each making the other stronger and fouler.',
  rhyhorn:     'Once it starts running it cannot turn, and it usually forgets why it started.',
  rhydon:      'The horn drills through rock. The hide shrugs off heat that would melt the rock.',
  chansey:     'It carries an egg that is genuinely nourishing, and gives it away to the injured.',
  tangela:     'The vines are constantly growing and constantly being torn off, and it does not seem to mind.',
  kangaskhan:  'Approaching the young is the single most reliable way to be badly hurt in Kanto.',
  horsea:      'It shoots ink upward when startled, which works underwater and embarrasses it in air.',
  seadra:      'Every spine carries venom, and it sleeps wedged in coral with all of them pointing out.',
  goldeen:     'It looks placid until it decides to move, and then the horn arrives before you do.',
  seaking:     'It hollows a nest in a riverbed with that horn and guards it through the whole season.',
  staryu:      'The core at its centre glows in time with something, and nobody has worked out what.',

  // ---- #121-140 ----------------------------------------------------------
  starmie:     'The core pulses in a pattern that repeats. Several people have devoted careers to it.',
  mrmime:      'The barrier is real, solid and invisible, and walking into one is a genuine hazard.',
  scyther:     'It moves faster than the eye tracks, so what you see is where it has already been.',
  jynx:        'It moves in a rhythm that is difficult to look away from, which is rather the point.',
  electabuzz:  'It is drawn to power lines and substations, and outages in Kanto are often its fault.',
  magmar:      'It is born in fire and shimmers with heat, so its outline is never quite steady.',
  pinsir:      'The pincers grip and then squeeze, and there is no leverage that gets you out.',
  tauros:      'It whips itself with its own tails to work up a rage before charging.',
  magikarp:    'Utterly hopeless in a fight, and yet somehow there are more of them than anything else.',
  gyarados:    'Whatever happens during that change leaves it furious, and it stays furious.',
  lapras:      'Gentle, intelligent, and now rare, because people found it easy to catch.',
  ditto:       'It rearranges its own cells to copy anything it sees, and gets it wrong when distracted.',
  eevee:       'Its genes are unusually unstable, which is why exposure to a stone can rewrite it entirely.',
  vaporeon:    'Its cells are so close to water that in still water it becomes effectively invisible.',
  jolteon:     'The fur stands up and holds a charge, and every hair can be fired like a needle.',
  flareon:     'It stores fire in a sac in its chest and runs hot enough that rain steams off it.',
  porygon:     'Made rather than born. It is entirely code, and it can move through systems as easily as rooms.',
  omanyte:     'Brought back from a shell in the rock. It swims by pulling with all ten tentacles at once.',
  omastar:     'The shell eventually grew too heavy to carry, which is thought to be why it died out.',
  kabuto:      'The eyes on its back still work, having spent three hundred million years underground.',

  // ---- #141-151 ----------------------------------------------------------
  kabutops:    'It hunted by slicing and drinking, and the scythes are as sharp now as they were then.',
  aerodactyl:  'Revived from a tooth in amber. It is exactly as aggressive as the fossil record suggested.',
  snorlax:     'It eats, it sleeps, and it does not move for anything, including roads.',
  articuno:    'It is said to appear to travellers lost in the snow, though accounts differ on what happens next.',
  zapdos:      'It nests in the storm itself, and the lightning is not something it summons but something it is.',
  moltres:     'Its wings trail fire, and the old story is that it comes back from its own ashes each spring.',
  dratini:     'Considered a myth until one was pulled from a lake. It sheds its skin as it grows.',
  dragonair:   'Fishermen say the weather changes when it surfaces, and they say it without smiling.',
  dragonite:   'It crosses oceans without stopping and has a documented habit of guiding lost ships home.',
  mewtwo:      'Made in a laboratory from something older, and it has never forgiven anyone for it.',
  mew:         'It carries the genetic code of every Pokémon, and it has been seen perhaps a dozen times.'
};
