// pokemon-kanto — tools/gen_badges.js
// Bakes FireRed's eight badge sprites into js/data/sprites_badges.js, in the
// same palette-and-rows format as the rest of the baked art.
//
// These are BAKED rather than streamed, unlike the trainer portraits and the
// overworld sheets. A badge case that says "you have five of eight" is the one
// screen a player opens to find out where they stand, and it has to draw the
// same way on a slow connection, offline, and in a headless browser. Eight
// 16x16 sprites cost almost nothing to carry.
//
//     node tools/gen_badges.js
//
// Re-run only if the source art changes; the output is committed.

'use strict';

const fs = require('fs');
const path = require('path');
const png = require('./png');

const SRC = 'https://raw.githubusercontent.com/pret/pokefirered/master/graphics/trainer_card/badges.png';
const CACHE = path.join(__dirname, 'cache', 'pokefirered__badges.png');
const DEST = path.join(__dirname, '..', 'js', 'data', 'sprites_badges.js');

// In gym order, which is the order they sit on the sheet.
const BADGES = ['boulder', 'cascade', 'thunder', 'rainbow', 'soul', 'marsh', 'volcano', 'earth'];

// badges.png is GREYSCALE. GBA art is an index map, and the colour arrives at
// runtime from whichever palette the trainer card is using — so all eight
// badges share one five-tone ramp in the file and come out looking like
// pewter. The SHAPES are the real thing and that is what is worth having; the
// colour has to be put back.
//
// So each badge's four shading tones are mapped onto its own colours, darkest
// to brightest. The outline stays black, as it is in the source.
const TONE = { '#7b7b7b': 0, '#b4b4b4': 1, '#d5d5d5': 2, '#ffffff': 3 };
const RAMP = {
  // Pewter's badge really is grey stone, so this one only gains a little warmth.
  boulder: ['#6d6a63', '#9c988e', '#c4c0b4', '#eceade'],
  cascade: ['#1c5ea8', '#3f90d8', '#7fc8f0', '#dff0ff'],
  thunder: ['#a86000', '#e09818', '#f8c840', '#fff0b8'],
  // The RAINBOW BADGE is a flower with differently coloured petals, and its
  // tones sit on different petals rather than shading one surface — so this is
  // the one badge whose ramp is four HUES instead of four brightnesses.
  rainbow: ['#3878c0', '#48a838', '#e85830', '#f8d040'],
  soul:    ['#a02858', '#d85888', '#f890b8', '#ffd8e8'],
  marsh:   ['#906018', '#c89828', '#f0c860', '#fff0c0'],
  volcano: ['#a02818', '#d84820', '#f88040', '#ffd0a0'],
  earth:   ['#206828', '#48a038', '#90d060', '#d8f0b0']
};
// '.' is transparent, so it is never handed out as a colour.
const CHARS = 'abcdefghijklmnopqrstuvwxyz0123456789';

(async function main() {
  if (!fs.existsSync(CACHE)) {
    const res = await fetch(SRC);
    if (!res.ok) throw new Error(`fetch badges.png: HTTP ${res.status}`);
    fs.mkdirSync(path.dirname(CACHE), { recursive: true });
    fs.writeFileSync(CACHE, Buffer.from(await res.arrayBuffer()));
  }
  const img = png.read(CACHE);
  const FW = 16;
  const n = img.w / FW;
  if (n !== BADGES.length || img.h !== 16) {
    throw new Error(`expected ${BADGES.length} 16x16 badges, got ${img.w}x${img.h}`);
  }

  const blocks = [];
  for (let f = 0; f < n; f++) {
    // One char per distinct colour in THIS badge, so each palette stays small
    // and readable rather than sharing one big table nobody can follow.
    const seen = new Map();
    const rows = [];
    for (let y = 0; y < 16; y++) {
      let row = '';
      for (let x = 0; x < FW; x++) {
        let c = img.hex(f * FW + x, y);
        if (!c) { row += '.'; continue; }
        if (TONE[c] !== undefined) {
          const ramp = RAMP[BADGES[f]];
          if (!ramp) throw new Error(`no colour ramp for ${BADGES[f]}`);
          c = ramp[TONE[c]];
        } else if (c !== '#000000') {
          throw new Error(`${BADGES[f]}: unexpected colour ${c} — the source art is no longer the flat greyscale this assumes`);
        }
        if (!seen.has(c)) {
          if (seen.size >= CHARS.length) throw new Error(`${BADGES[f]}: too many colours`);
          seen.set(c, CHARS[seen.size]);
        }
        row += seen.get(c);
      }
      rows.push(row);
    }
    const pal = [...seen].map(([hex, ch]) => `${ch}: '${hex}'`).join(', ');
    blocks.push(
      `  B('badge_${BADGES[f]}', { ${pal} }, [\n` +
      rows.map(r => `    '${r}'`).join(',\n') +
      '\n  ]);'
    );
  }

  const out = `// GENERATED by tools/gen_badges.js from pret/pokefirered's
// graphics/trainer_card/badges.png — do not hand-edit.
// pokemon-kanto — sprites_badges.js
// The eight KANTO badges, at the size FireRed draws them on the trainer card.
//
// Baked rather than streamed. The badge case is where a player goes to find
// out how far through the game they are, and it has to look the same offline,
// on a slow connection, and in a headless browser taking screenshots.

(function () {
  function B(name, pal, rows) {
    // The 'imported' flag says these carry FireRed's palette rather than
    // this game's master one, on purpose - see the ART pass in check.js.
    G.ART[name] = { w: 16, h: 16, pal: pal, px: rows, imported: true };
  }

${blocks.join('\n\n')}
})();
`;
  fs.writeFileSync(DEST, out);
  console.log(`wrote ${BADGES.length} badges to ${path.relative(process.cwd(), DEST)}`);
})();
