// pokemon-kanto — tools/gen_data.js
// Emits the generated half of js/data/ from the Red/Blue disassembly:
//
//   types.js            15-type Gen 1 chart (+ our deliberate un-bugging)
//   moves.js            all 165 Gen 1 moves with engine effect descriptors
//   species_base.js     the defSpecies factory
//   species_001_050.js  \
//   species_051_100.js   >  151 species, real ROM stats/learnsets/evolutions
//   species_101_151.js  /
//   kanto_dex.js        national dex order
//
// Run: node tools/gen_data.js
// NEVER hand-edit the files it writes — edit this, or tools/blurbs.js, and re-run.

'use strict';

const fs = require('fs');
const path = require('path');
const pokered = require('./pokered.js');
const BLURBS = require('./blurbs.js');

const OUT = path.join(__dirname, '..', 'js', 'data');
const HEAD = '// GENERATED by tools/gen_data.js from pret/pokered — do not hand-edit.\n';

// =========================================================== type chart ====

// Gen 1 has 15 types. Two matchups are DELIBERATELY changed from the ROM:
//
//  * Ghost -> Psychic was 0x in Red/Blue. That is a straight data error (the
//    designers clearly intended 2x — it's why Ghost-types learn no Ghost moves
//    worth using and why Psychic went unchecked for a whole generation). We
//    set it to 2x, which is what every later game does.
//  * Poison -> Bug was 2x in Gen 1 and Bug -> Poison 2x as well. That mutual
//    relationship is genuinely Gen 1 flavour, not a bug, so it STAYS.
const CHART_FIXES = {
  ghost: { psychic: 2 }
};

// Gen 1 decides physical/special by TYPE, not per-move.
// TM/HM move order, from the add_hm/add_tm macro calls in
// constants/item_constants.asm. HMs come FIRST in the item table even though
// they are numbered after the TMs, which is why the compatibility bitfield in
// base_stats reads in this order.
const TM_HM_ORDER = [
  'CUT', 'FLY', 'SURF', 'STRENGTH', 'FLASH',
  'MEGA_PUNCH', 'RAZOR_WIND', 'SWORDS_DANCE', 'WHIRLWIND', 'MEGA_KICK',
  'TOXIC', 'HORN_DRILL', 'BODY_SLAM', 'TAKE_DOWN', 'DOUBLE_EDGE',
  'BUBBLEBEAM', 'WATER_GUN', 'ICE_BEAM', 'BLIZZARD', 'HYPER_BEAM',
  'PAY_DAY', 'SUBMISSION', 'COUNTER', 'SEISMIC_TOSS', 'RAGE',
  'MEGA_DRAIN', 'SOLARBEAM', 'DRAGON_RAGE', 'THUNDERBOLT', 'THUNDER',
  'EARTHQUAKE', 'FISSURE', 'DIG', 'PSYCHIC_M', 'TELEPORT',
  'MIMIC', 'DOUBLE_TEAM', 'REFLECT', 'BIDE', 'METRONOME',
  'SELFDESTRUCT', 'EGG_BOMB', 'FIRE_BLAST', 'SWIFT', 'SKULL_BASH',
  'SOFTBOILED', 'DREAM_EATER', 'SKY_ATTACK', 'REST', 'THUNDER_WAVE',
  'PSYWAVE', 'EXPLOSION', 'ROCK_SLIDE', 'TRI_ATTACK', 'SUBSTITUTE'
];

const PHYS_TYPES = ['normal', 'fighting', 'flying', 'poison', 'ground', 'rock', 'bug', 'ghost'];

function emitTypes(chart) {
  const order = ['normal', 'fire', 'water', 'grass', 'electric', 'ice', 'fighting',
    'poison', 'ground', 'flying', 'psychic', 'bug', 'rock', 'ghost', 'dragon'];

  const merged = {};
  for (const a of order) merged[a] = Object.assign({}, chart[a] || {});
  for (const a in CHART_FIXES) Object.assign(merged[a], CHART_FIXES[a]);

  const rows = order.map(a => {
    const row = merged[a] || {};
    const keys = order.filter(d => d in row);
    const body = keys.map(d => `${d}: ${row[d]}`).join(', ');
    return `    ${(a + ':').padEnd(10)}{ ${body} }`;
  }).join(',\n');

  return HEAD + `// pokemon-kanto — types.js
// The Gen 1 chart, straight from data/types/type_matchups.asm. Fifteen types:
// there is no Dark, no Steel, no Fairy. Bug and Poison are mutually super-
// effective, Ice does not resist Fire, and Psychic is weak only to Bug.
//
// One matchup is deliberately corrected: Ghost -> Psychic, which Red/Blue
// shipped as 0x. That was a data error, and living with it means Psychic-types
// have no counterplay at all for the whole game. Here it is 2x.

(function () {
  G.TYPE_ORDER = ${JSON.stringify(order).replace(/","/g, "', '").replace(/\["/, "['").replace(/"\]/, "']")};

  // G.TYPE_CHART[attacker][defender] = multiplier; missing = 1.
  G.TYPE_CHART = {
${rows}
  };

  // Gen 1: the move's TYPE decides whether it uses Attack or Special.
  // There is no per-move category and no way to override it.
  G.PHYS_TYPES = { ${PHYS_TYPES.map(t => t + ': 1').join(', ')} };
  G.isPhysical = function (type) { return !!G.PHYS_TYPES[type]; };

  G.typeEff = function (moveType, defTypes) {
    var mult = 1;
    var row = G.TYPE_CHART[moveType] || {};
    for (var i = 0; i < defTypes.length; i++) {
      var m = row[defTypes[i]];
      if (m != null) mult *= m;
    }
    return mult;
  };
})();
`;
}

// ================================================================ moves ====

// pokered effect constant -> the engine's effect descriptor (battle.js reads
// these). `null` means "plain damage, no rider".
function moveEffect(mv) {
  const st = (status, chance) => ({ kind: 'status', status, chance });
  const stage = (target, stat, delta, chance) => ({ kind: 'stages', target, stat, delta, chance });
  // Gen 1 side-effect chances: ...1 variants are 10%, ...2 variants are 30%.
  const E = {
    NO_ADDITIONAL_EFFECT: null,
    SWIFT_EFFECT: null,           // accuracy is forced to 101 below
    HYPER_BEAM_EFFECT: { kind: 'recharge' },

    // --- status ---
    SLEEP_EFFECT: st('slp'),
    POISON_EFFECT: mv.const === 'TOXIC' ? { kind: 'status', status: 'tox' } : st('psn'),
    PARALYZE_EFFECT: st('par'),
    CONFUSION_EFFECT: { kind: 'confuse' },
    POISON_SIDE_EFFECT1: st('psn', 20),
    POISON_SIDE_EFFECT2: st('psn', 40),
    BURN_SIDE_EFFECT1: st('brn', 10),
    BURN_SIDE_EFFECT2: st('brn', 30),
    FREEZE_SIDE_EFFECT1: st('frz', 10),
    PARALYZE_SIDE_EFFECT1: st('par', 10),
    PARALYZE_SIDE_EFFECT2: st('par', 30),
    CONFUSION_SIDE_EFFECT: { kind: 'confuse', chance: 10 },
    FLINCH_SIDE_EFFECT1: { kind: 'flinch', chance: 10 },
    FLINCH_SIDE_EFFECT2: { kind: 'flinch', chance: 30 },

    // --- stat stages ---
    ATTACK_UP1_EFFECT: stage('self', 'atk', 1),
    ATTACK_UP2_EFFECT: stage('self', 'atk', 2),
    DEFENSE_UP1_EFFECT: stage('self', 'def', 1),
    DEFENSE_UP2_EFFECT: stage('self', 'def', 2),
    SPEED_UP2_EFFECT: stage('self', 'spe', 2),
    SPECIAL_UP1_EFFECT: stage('self', 'spc', 1),
    SPECIAL_UP2_EFFECT: stage('self', 'spc', 2),
    EVASION_UP1_EFFECT: stage('self', 'eva', 1),
    ATTACK_DOWN1_EFFECT: stage('foe', 'atk', -1),
    DEFENSE_DOWN1_EFFECT: stage('foe', 'def', -1),
    DEFENSE_DOWN2_EFFECT: stage('foe', 'def', -2),
    SPEED_DOWN1_EFFECT: stage('foe', 'spe', -1),
    ACCURACY_DOWN1_EFFECT: stage('foe', 'acc', -1),
    ATTACK_DOWN_SIDE_EFFECT: stage('foe', 'atk', -1, 33),
    DEFENSE_DOWN_SIDE_EFFECT: stage('foe', 'def', -1, 33),
    SPEED_DOWN_SIDE_EFFECT: stage('foe', 'spe', -1, 33),
    SPECIAL_DOWN_SIDE_EFFECT: stage('foe', 'spc', -1, 33),

    // --- damage shapes ---
    DRAIN_HP_EFFECT: { kind: 'drain', frac: 0.5 },
    DREAM_EATER_EFFECT: { kind: 'drain', frac: 0.5, requires: 'slp' },
    RECOIL_EFFECT: { kind: 'recoil', frac: 0.25 },
    JUMP_KICK_EFFECT: { kind: 'crash', frac: 0.125 },
    TWO_TO_FIVE_ATTACKS_EFFECT: { kind: 'multiHit' },
    ATTACK_TWICE_EFFECT: { kind: 'multiHit', times: 2 },
    TWINEEDLE_EFFECT: { kind: 'multiHit', times: 2, rider: st('psn', 20) },
    OHKO_EFFECT: { kind: 'ohko' },
    SUPER_FANG_EFFECT: { kind: 'fixed', mode: 'half' },
    EXPLODE_EFFECT: { kind: 'explode' },
    TRAPPING_EFFECT: { kind: 'trap' },
    THRASH_PETAL_DANCE_EFFECT: { kind: 'thrash' },
    RAGE_EFFECT: { kind: 'rage' },
    PAY_DAY_EFFECT: { kind: 'payday' },
    BIDE_EFFECT: { kind: 'bide' },

    // --- two-turn ---
    CHARGE_EFFECT: { kind: 'charge', vanish: mv.const === 'DIG' },
    FLY_EFFECT: { kind: 'charge', vanish: true },

    // --- field / self ---
    HEAL_EFFECT: mv.const === 'REST' ? { kind: 'rest' } : { kind: 'heal', frac: 0.5 },
    LEECH_SEED_EFFECT: { kind: 'leechseed' },
    REFLECT_EFFECT: { kind: 'screen', which: 'reflect' },
    LIGHT_SCREEN_EFFECT: { kind: 'screen', which: 'lightscreen' },
    MIST_EFFECT: { kind: 'mist' },
    HAZE_EFFECT: { kind: 'haze' },
    FOCUS_ENERGY_EFFECT: { kind: 'focusenergy' },
    SUBSTITUTE_EFFECT: { kind: 'substitute' },
    DISABLE_EFFECT: { kind: 'disable' },
    SPLASH_EFFECT: { kind: 'splash' },
    CONVERSION_EFFECT: { kind: 'conversion' },
    TRANSFORM_EFFECT: { kind: 'transform' },
    MIMIC_EFFECT: { kind: 'mimic' },
    METRONOME_EFFECT: { kind: 'metronome' },
    MIRROR_MOVE_EFFECT: { kind: 'mirrormove' },
    SWITCH_AND_TELEPORT_EFFECT: { kind: 'switchout' },

    // --- fixed damage ---
    SPECIAL_DAMAGE_EFFECT: {
      SONICBOOM: { kind: 'fixed', mode: 'const', value: 20 },
      DRAGON_RAGE: { kind: 'fixed', mode: 'const', value: 40 },
      SEISMIC_TOSS: { kind: 'fixed', mode: 'level' },
      NIGHT_SHADE: { kind: 'fixed', mode: 'level' },
      PSYWAVE: { kind: 'fixed', mode: 'psywave' }
    }[mv.const] || { kind: 'fixed', mode: 'level' }
  };

  if (!(mv.effect in E)) throw new Error(`unmapped move effect: ${mv.effect} (${mv.name})`);
  return E[mv.effect];
}

// Gen 1 quirks worth carrying, and the handful we correct.
const MOVE_PRIORITY = { quickattack: 1, hyperfang: 0 };
const HIGH_CRIT = ['karatechop', 'razorleaf', 'crabhammer', 'slash'];

function emitMoves(moves) {
  const body = moves.map(mv => {
    const eff = moveEffect(mv);
    const isHighCrit = HIGH_CRIT.includes(mv.key);
    // Swift ignores accuracy entirely; the engine reads acc > 100 as "never miss".
    const acc = mv.effect === 'SWIFT_EFFECT' ? 101 : mv.acc;
    const prio = MOVE_PRIORITY[mv.key] || 0;

    let effStr;
    if (isHighCrit && !eff) effStr = "{ kind: 'highCrit' }";
    else if (isHighCrit) effStr = json(Object.assign({ highCrit: true }, eff));
    else effStr = eff ? json(eff) : '';

    const args = [
      q(mv.key).padEnd(16),
      q(mv.name).padEnd(16),
      q(mv.type).padEnd(11),
      String(mv.power).padStart(3),
      String(acc).padStart(4),
      String(mv.pp).padStart(3)
    ];
    if (effStr || prio) args.push(String(prio));
    if (effStr) args.push(effStr);
    return `  mv(${args.join(', ')});`;
  }).join('\n');

  return HEAD + `// pokemon-kanto — moves.js
// All 165 Gen 1 moves, from data/moves/moves.asm. Power, accuracy, PP and type
// are the ROM values. Category is decided by TYPE (see types.js), so no move
// carries a category field.
//
// Effect descriptors understood by battle.js — see the switch in applyEffect():
//   status | confuse | stages | flinch | drain | recoil | crash | multiHit
//   ohko | fixed | explode | trap | thrash | rage | payday | bide | charge
//   recharge | heal | rest | leechseed | screen | mist | haze | focusenergy
//   substitute | disable | splash | conversion | transform | mimic | metronome
//   mirrormove | switchout | highCrit
//
// Accuracy 101 means "cannot miss" (Swift). Gen 1's 1/256 whiff on nominally
// 100%-accurate moves is NOT reproduced — it is a rounding bug, not a feature.

(function () {
  var M = G.MOVES = {};
  function mv(id, name, type, power, acc, pp, prio, effect) {
    M[id] = { id: id, name: name, type: type, power: power, acc: acc, pp: pp, priority: prio || 0, effect: effect || null };
  }

${body}

  // Struggle is not in the ROM move table but the engine needs it.
  mv('struggle', 'Struggle', 'normal', 50, 100, 99, 0, { kind: 'recoil', frac: 0.5 });
})();
`;
}

// Compact single-line JSON with JS-style unquoted keys and single quotes.
// Keys whose value is undefined are dropped rather than emitted as literal
// `undefined` (an optional `chance` means "always", not "chance of undefined").
function json(o) {
  return '{ ' + Object.keys(o).filter(k => o[k] !== undefined).map(k => {
    const v = o[k];
    const val = typeof v === 'string' ? q(v)
      : (v && typeof v === 'object') ? json(v)
        : String(v);
    return `${k}: ${val}`;
  }).join(', ') + ' }';
}

// Single-quoted JS string literal, apostrophes escaped (Farfetch'd).
const q = s => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

// ============================================================== species ====

const GROWTH = {
  MEDIUM_FAST: 'mediumFast', MEDIUM_SLOW: 'mediumSlow', FAST: 'fast', SLOW: 'slow',
  SLIGHTLY_FAST: 'fast', SLIGHTLY_SLOW: 'slow'
};

const LEGENDARY = ['articuno', 'zapdos', 'moltres', 'mewtwo', 'mew'];
const STARTERS = ['bulbasaur', 'ivysaur', 'venusaur', 'charmander', 'charmeleon',
  'charizard', 'squirtle', 'wartortle', 'blastoise'];

const STONE_ITEM = {
  FIRE_STONE: 'firestone', WATER_STONE: 'waterstone', THUNDER_STONE: 'thunderstone',
  LEAF_STONE: 'leafstone', MOON_STONE: 'moonstone'
};

function rarityOf(s) {
  if (LEGENDARY.includes(s.key)) return 'legendary';
  if (STARTERS.includes(s.key)) return 'starter';
  if (s.catchRate >= 190) return 'common';
  if (s.catchRate >= 120) return 'uncommon';
  if (s.catchRate >= 60) return 'rare';
  return 'elusive';
}

// Trade evolutions have nobody to trade with, so they become level-ups. The
// levels are the community-standard choices used by every single-player hack:
// late enough that you still play the middle stage, early enough to matter.
const TRADE_LEVEL = { kadabra: 37, machoke: 40, graveler: 40, haunter: 38 };

function speciesEvos(s) {
  return s.evos.map(e => {
    if (e.how === 'level') return { how: 'level', level: e.level, into: e.into };
    if (e.how === 'trade') return { how: 'level', level: TRADE_LEVEL[s.key] || 38, into: e.into, wasTrade: true };
    return { how: 'stone', item: STONE_ITEM[e.item] || 'moonstone', into: e.into };
  });
}

function emitSpeciesBase() {
  return HEAD + `// pokemon-kanto — species_base.js
// The factory the three generated species files call. Gen 1 has ONE Special
// stat; we mirror it into spa and spd so the rest of the engine (which is
// written for the modern split) needs no special-casing, and so Amnesia and
// Growth correctly raise offence and defence together.

(function () {
  G.SPECIES = G.SPECIES || {};
  G.DEX_ORDER = G.DEX_ORDER || [];

  // defSpecies(dex, key, name, types, rarity, [hp,atk,def,spc,spe],
  //            evos, learnset, blurb, { catchRate, expYield, growth })
  //   evos: array of { how:'level', level, into } or { how:'stone', item, into }
  G.defSpecies = function (dex, key, name, types, rarity, base, evos, learnset, blurb, opts) {
    opts = opts || {};
    var spc = base[3];
    G.SPECIES[key] = {
      id: dex, key: key, name: name, types: types, rarity: rarity,
      base: { hp: base[0], atk: base[1], def: base[2], spa: spc, spd: spc, spe: base[4] },
      spc: spc,                       // the single Gen 1 Special, for stat growth
      catchRate: opts.catchRate,
      expYield: opts.expYield,
      evos: evos || [],
      // Back-compat single-path fields, so older engine code keeps working.
      evolvesTo: (evos && evos[0] && evos[0].how === 'level') ? evos[0].into : null,
      evolveLevel: (evos && evos[0] && evos[0].how === 'level') ? evos[0].level : 0,
      learnset: learnset,
      dex: blurb,
      growth: opts.growth || 'mediumFast'
    };
    G.DEX_ORDER.push(key);
  };
})();
`;
}

function emitSpeciesChunk(list, species, from, to) {
  const body = list.map(key => {
    const s = species[key];
    const evos = speciesEvos(s);
    const blurb = BLURBS[key];
    if (!blurb) throw new Error(`missing dex blurb for ${key} — add it to tools/blurbs.js`);

    const types = `[${s.types.map(q).join(', ')}]`;
    const base = `[${[s.hp, s.atk, s.def, s.spc, s.spe].map(n => String(n).padStart(3)).join(', ')}]`;
    const evoStr = evos.length ? `[${evos.map(e => json(e)).join(', ')}]` : 'null';
    const ls = s.learnset.length
      ? `[${s.learnset.map(([l, m]) => `[${l}, '${m}']`).join(', ')}]`
      : '[]';
    const opts = `{ catchRate: ${s.catchRate}, expYield: ${s.baseExp}, growth: ${GROWTH[s.growth] === 'mediumFast' ? 'MF' : GROWTH[s.growth] === 'mediumSlow' ? 'MS' : GROWTH[s.growth] === 'fast' ? 'FA' : 'SL'} }`;

    return `  sp(${String(s.dex).padStart(3)}, ${q(key)}, ${q(s.name)}, ${types}, ${q(rarityOf(s))}, ${base},\n` +
      `     ${evoStr},\n` +
      `     ${ls},\n` +
      `     ${JSON.stringify(blurb)},\n` +
      `     ${opts});`;
  }).join('\n\n');

  return HEAD + `// pokemon-kanto — species_${pad(from)}_${pad(to)}.js  (national dex #${from}-${to})
// Base stats, types, catch rates, base experience, growth rates, evolutions and
// level-up learnsets are the Red/Blue values. Dex blurbs are original writing.
//
// Stat order is Gen 1's own: [HP, Attack, Defense, SPECIAL, Speed].

(function () {
  var sp = G.defSpecies;
  var MF = 'mediumFast', MS = 'mediumSlow', FA = 'fast', SL = 'slow';

${body}
})();
`;
}

const pad = n => String(n).padStart(3, '0');

function emitDex(dexOrder) {
  const rows = [];
  for (let i = 0; i < dexOrder.length; i += 6) {
    rows.push('    ' + dexOrder.slice(i, i + 6).map(k => `'${k}'`).join(', '));
  }
  return HEAD + `// pokemon-kanto — kanto_dex.js
// National dex order, #1-151. The Pokédex screen and the sprite loader key on
// the index in this list.

(function () {
  G.KANTO_DEX = [
${rows.join(',\n')}
  ];
})();
`;
}

// ========================================================== TMs and HMs ====

// The 50 TMs and 5 HMs, in ROM order, and per-species compatibility straight
// from the `tmhm` line in each base_stats file. Nothing here is invented: if
// Red/Blue let a Gastly learn MEGA DRAIN, so do we.
//
// TMs are SINGLE USE, as they were in Gen 1 — the whole reason a TM felt like
// treasure. HMs are permanent and cannot be forgotten.
function emitTms(species, dexOrder) {
  // PSYCHIC_M is the ROM's disambiguation between the MOVE and PSYCHIC_TYPE.
  // Mechanically renaming it would give us a move called "psychicm" that no
  // species learnset ever references.
  const CONST_FIX = { PSYCHIC_M: 'psychic' };
  const list = TM_HM_ORDER.map((c, i) => {
    const id = i < 5 ? 'hm0' + (i + 1) : 'tm' + String(i - 4).padStart(2, '0');
    return { id: id, move: CONST_FIX[c] || pokered.moveKey(c), constant: c };
  });

  const compat = dexOrder.map(key => {
    const s = species[key];
    // Mew's row ends in UNUSED — the ROM pads its bitfield out to a whole
    // byte and the assembler needs a name for the spare bit. It is not a move.
    const learn = (s.tms || []).filter(c => c !== 'UNUSED').map(c => {
      const hit = list.find(e => e.constant === c);
      if (!hit) throw new Error(`${key} lists TM/HM move ${c}, which is not in the TM table`);
      return hit.id;
    });
    return `    ${key}: ${JSON.stringify(learn).replace(/","/g, "', '").replace(/^\["/, "['").replace(/"\]$/, "']").replace(/^\[\]$/, '[]')}`;
  }).join(',\n');

  return HEAD + `// pokemon-kanto — tms.js
// The 50 TMs and 5 HMs of Kanto, and which species can learn each.
//
// Gen 1 rules, kept deliberately:
//   * a TM is CONSUMED when it is used, so every one is a real decision
//   * an HM is permanent, reusable, and its move cannot be forgotten
//   * compatibility is the ROM's own table, quirks included — Mr. Mime learns
//     THUNDERBOLT, Charizard never learns a FLYING move worth the name

(function () {
  G.TM_MOVES = {
${list.map(e => `    ${e.id}: ${q(e.move)}`).join(',\n')}
  };

  // Field moves. The badge requirement is Gen 1's own: you cannot SURF into
  // deep water on the strength of an HM alone, the region has to decide you
  // are allowed to.
  G.FIELD_MOVES = {
    cut:      { hm: 'hm01', move: 'cut',      badge: 'badge2', badgeName: 'CASCADE BADGE' },
    fly:      { hm: 'hm02', move: 'fly',      badge: 'badge3', badgeName: 'THUNDER BADGE' },
    surf:     { hm: 'hm03', move: 'surf',     badge: 'badge5', badgeName: 'SOUL BADGE' },
    strength: { hm: 'hm04', move: 'strength', badge: 'badge4', badgeName: 'RAINBOW BADGE' },
    flash:    { hm: 'hm05', move: 'flash',    badge: 'badge1', badgeName: 'BOULDER BADGE' }
  };

  G.TM_COMPAT = {
${compat}
  };

  // A mon carries its species in \`sp\`. This read it as \`mon.species\`, which is
  // undefined on every mon the game has ever made, so the lookup fell to an
  // empty list and the answer was NO for all 151 species and all 55 machines:
  // nothing in KANTO could be taught a TM or an HM. The compatibility tables
  // underneath were correct the whole time — CHARMELEON has always had tm01 —
  // which is why this looked like bad data rather than a one-word typo.
  //
  // Takes either a mon or a bare species key, since half the callers of a
  // question like this only have the species.
  G.canLearnTm = function (mon, tmId) {
    var key = typeof mon === 'string' ? mon : (mon && mon.sp);
    if (!key || !G.SPECIES[key]) return false;
    return (G.TM_COMPAT[key] || []).indexOf(tmId) !== -1;
  };
})();
`;
}

// ======================================================= dex metadata ======

// Genus, height and weight, from data/pokemon/dex_entries.asm. The ROM stores
// height as (feet, inches) and weight in TENTHS of a pound, which is why the
// numbers look odd until you divide: Rhydon is 6'3" and 265.0 lb.
//
// These exist so the Pokedex can be a PAGE rather than a list. 151 original
// dex blurbs were written for this project and until now nothing displayed
// them properly.
async function emitDexMeta(dexOrder) {
  const text = await pokered.raw('data/pokemon/dex_entries.asm');
  const ls = pokered.lines(text);
  const byName = {};
  for (let i = 0; i < ls.length; i++) {
    const m = ls[i].match(/^([A-Za-z0-9]+)DexEntry:$/);
    if (!m) continue;
    const genus = (ls[i + 1].match(/^db "([^"@]*)@?"/) || [])[1];
    const hw = (ls[i + 2].match(/^db\s+(\d+)\s*,\s*(\d+)$/) || []);
    const wt = (ls[i + 3].match(/^dw\s+(\d+)$/) || []);
    if (!genus || !hw[1] || !wt[1]) continue;
    byName[pokered.monKey(m[1])] = {
      genus: genus.charAt(0) + genus.slice(1).toLowerCase(),
      ft: +hw[1], inch: +hw[2], lb: +wt[1] / 10
    };
  }
  const rows = dexOrder.map(k => {
    const d = byName[k];
    if (!d) throw new Error(`no dex entry data for ${k}`);
    return `    ${k}: { genus: ${q(d.genus)}, ft: ${d.ft}, inch: ${d.inch}, lb: ${d.lb} }`;
  }).join(',\n');

  return HEAD + `// pokemon-kanto — dex_meta.js
// The species line, height and weight the POKéDEX shows on an entry page.
// Straight from the ROM: heights are feet and inches, weights are pounds,
// exactly as the English Red/Blue printed them.

(function () {
  G.DEX_META = {
${rows}
  };
})();
`;
}

// ================================================================= main ====

async function main() {
  const d = await pokered.load();

  const write = (name, text) => {
    fs.writeFileSync(path.join(OUT, name), text);
    console.log(`  ${name.padEnd(24)} ${text.split('\n').length} lines`);
  };

  console.log('generating:');
  write('types.js', emitTypes(d.chart));
  write('moves.js', emitMoves(d.moves));
  write('species_base.js', emitSpeciesBase());
  write('species_001_050.js', emitSpeciesChunk(d.dexOrder.slice(0, 50), d.species, 1, 50));
  write('species_051_100.js', emitSpeciesChunk(d.dexOrder.slice(50, 100), d.species, 51, 100));
  write('species_101_151.js', emitSpeciesChunk(d.dexOrder.slice(100, 151), d.species, 101, 151));
  write('kanto_dex.js', emitDex(d.dexOrder));
  write('tms.js', emitTms(d.species, d.dexOrder));
  write('dex_meta.js', await emitDexMeta(d.dexOrder));

  const wild = await pokered.loadWild([...new Set(Object.values(WILD_MAPS))]);
  write('encounters.js', emitEncounters(wild));

  // ---- report ----
  const stoneEvos = d.dexOrder.filter(k => d.species[k].evos.some(e => e.how === 'item'));
  const tradeEvos = d.dexOrder.filter(k => d.species[k].evos.some(e => e.how === 'trade'));
  console.log(`\nmoves: ${d.moves.length}   species: ${d.dexOrder.length}`);
  console.log(`stone evolutions (${stoneEvos.length}): ${stoneEvos.join(', ')}`);
  console.log(`trade evolutions -> level (${tradeEvos.length}): ${tradeEvos.join(', ')}`);
}

main().catch(e => { console.error('\nFAILED:', e.message); process.exit(1); });

// ========================================================== encounters =====
// Wild tables, straight from data/wild/maps/*.asm. Gen 1 gives every map a
// single encounter RATE (0-255, chance per step out of 256) and ten weighted
// SLOTS; the slot index decides its frequency, not the species. Slot weights
// are the ROM's: 20/20/15/15/10/10/5/5/4/1 percent.
//
// Left side is our map id, right side is the pokered file. Ids are inherited
// by warps and MUST NOT be renamed once maps exist.
const WILD_MAPS = {
  route1: 'Route1', route2: 'Route2', route3: 'Route3', route4: 'Route4',
  route5: 'Route5', route6: 'Route6', route7: 'Route7', route8: 'Route8',
  route9: 'Route9', route10: 'Route10', route11: 'Route11', route12: 'Route12',
  route13: 'Route13', route14: 'Route14', route15: 'Route15', route16: 'Route16',
  route17: 'Route17', route18: 'Route18', route21: 'Route21', route22: 'Route22',
  route23: 'Route23', route24: 'Route24', route25: 'Route25',
  viridianforest: 'ViridianForest',
  mtmoon1f: 'MtMoon1F', mtmoonb1f: 'MtMoonB1F', mtmoonb2f: 'MtMoonB2F',
  diglettscave: 'DiglettsCave',
  rocktunnel1f: 'RockTunnel1F', rocktunnelb1f: 'RockTunnelB1F',
  powerplant: 'PowerPlant',
  pokemontower3f: 'PokemonTower3F', pokemontower4f: 'PokemonTower4F',
  pokemontower5f: 'PokemonTower5F', pokemontower6f: 'PokemonTower6F',
  pokemontower7f: 'PokemonTower7F',
  seafoam1f: 'SeafoamIslands1F', seafoamb1f: 'SeafoamIslandsB1F',
  seafoamb2f: 'SeafoamIslandsB2F', seafoamb3f: 'SeafoamIslandsB3F',
  seafoamb4f: 'SeafoamIslandsB4F',
  mansion1f: 'PokemonMansion1F', mansion2f: 'PokemonMansion2F',
  mansion3f: 'PokemonMansion3F', mansionb1f: 'PokemonMansionB1F',
  victoryroad1f: 'VictoryRoad1F', victoryroad2f: 'VictoryRoad2F',
  victoryroad3f: 'VictoryRoad3F',
  ceruleancave1f: 'CeruleanCave1F', ceruleancave2f: 'CeruleanCave2F',
  ceruleancaveb1f: 'CeruleanCaveB1F',
  safarizonecenter: 'SafariZoneCenter', safarizoneeast: 'SafariZoneEast',
  safarizonenorth: 'SafariZoneNorth', safarizonewest: 'SafariZoneWest',
  searoutes: 'SeaRoutes'
};

const SLOT_PCT = [20, 20, 15, 15, 10, 10, 5, 5, 4, 1];

// Collapse the ten slots into one weighted entry per species, summing the
// weights of repeated species and taking their level range.
function foldSlots(slots) {
  const by = {};
  slots.forEach((s, i) => {
    const e = by[s.key] || (by[s.key] = { key: s.key, w: 0, min: s.level, max: s.level });
    e.w += SLOT_PCT[i] || 1;
    if (s.level < e.min) e.min = s.level;
    if (s.level > e.max) e.max = s.level;
  });
  return Object.values(by).sort((a, b) => b.w - a.w);
}

function emitEncounters(wild) {
  const blocks = [];
  for (const [id, file] of Object.entries(WILD_MAPS)) {
    const w = wild[file];
    if (!w || (!w.grass && !w.water)) continue;

    // The engine wants { rate, table:[{sp,min,max,w}] } with rate as a per-step
    // PROBABILITY. Gen 1 stores it as a byte out of 256, so convert.
    const NL = '\n';
    const section = (k) => {
      const rows = foldSlots(w[k].slots)
        .map(e => `      { sp: '${e.key}', min: ${e.min}, max: ${e.max}, w: ${e.w} }`)
        .join(',' + NL);
      return `rate: ${(w[k].rate / 256).toFixed(3)}, table: [` + NL + rows + NL + '    ]';
    };

    const parts = [];
    if (w.grass) parts.push('    ' + section('grass'));
    if (w.water) parts.push('    water: { ' + section('water') + ' }');
    blocks.push(`  ${id}: {` + NL + parts.join(',' + NL) + NL + '  }');
  }
  return HEAD + `// pokemon-kanto — encounters.js
// Wild encounter tables from data/wild/maps/*.asm. These are the real Red/Blue
// numbers: Route 1 really is Pidgey and Rattata at levels 2-5, and Route 22
// really does hide a 1-in-100 Nidoran before you have a single badge.
//
//   rate   : per-step encounter probability (the ROM byte, divided by 256)
//   table  : one entry per species; w is its summed percentage across the ten
//            ROM slots, min/max the level range over those slots
//   water  : the Surf table, same shape, used once you have HM03
//
// G.rollEncounter (overworld.js) picks by weight.

(function () {
  G.ENCOUNTERS = {
${blocks.join(',\n')}
  };
})();
`;
}
